# Generated by Django 3.2.6 on 2022-01-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, null=True)),
                ('surname', models.CharField(db_index=True, max_length=35)),
                ('other_names', models.CharField(max_length=70, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('res_addr', models.CharField(max_length=255, null=True)),
                ('res_area', models.CharField(max_length=80, null=True)),
                ('res_city', models.CharField(max_length=35, null=True)),
                ('res_state', models.CharField(max_length=35, null=True)),
                ('mobile_no1', models.CharField(max_length=33, null=True)),
                ('mobile_no2', models.CharField(max_length=33, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('stays_together', models.BooleanField(null=True)),
                ('relationship', models.CharField(max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'apps_Guardians',
                'ordering': ['surname'],
            },
        ),
    ]
