# Generated by Django 3.2.6 on 2022-01-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_guardians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(db_index=True, max_length=50, null=True, unique=True)),
                ('surname', models.CharField(db_index=True, max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=40, null=True)),
                ('stud_pic', models.ImageField(blank=True, default='images/static/default.png', null=True, upload_to='images')),
                ('dob', models.DateField(blank=True, db_index=True, default=None, null=True)),
                ('age', models.IntegerField(default=None, null=True)),
                ('gender', models.CharField(db_index=True, max_length=8)),
                ('email', models.EmailField(db_index=True, max_length=255, null=True)),
                ('phone_no', models.CharField(db_index=True, max_length=33, null=True)),
                ('bloodgroup', models.CharField(blank=True, max_length=5, null=True)),
                ('religion', models.CharField(blank=True, max_length=15, null=True)),
                ('res_addr_l1', models.CharField(max_length=255, null=True)),
                ('res_addr_l2', models.CharField(max_length=100, null=True)),
                ('res_city', models.CharField(max_length=35, null=True)),
                ('state_origin', models.CharField(max_length=30, null=True)),
                ('lga_origin', models.CharField(max_length=30, null=True)),
                ('nationality', models.CharField(max_length=30, null=True)),
                ('reg_steps', models.IntegerField(null=True)),
                ('reg_status', models.CharField(db_index=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('g_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='apps_guardians.guardians')),
            ],
            options={
                'db_table': 'apps_Students',
                'ordering': ['reg_no'],
            },
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(null=True)),
                ('session_id', models.CharField(max_length=15, null=True)),
                ('reg_no', models.CharField(max_length=50)),
                ('class_id', models.IntegerField(null=True)),
                ('enroll_date', models.DateField(blank=True, db_index=True, default=None)),
                ('status', models.CharField(db_index=True, max_length=50, null=True)),
                ('reg_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='apps_students.students')),
            ],
            options={
                'db_table': 'apps_Enrollments',
                'ordering': ['reg_no', 'session_id', 'class_id'],
            },
        ),
    ]
