# Generated by Django 3.2.6 on 2022-03-07 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0010_auto_20220204_1950'),
        ('apps_students', '0002_enrollments_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollments',
            name='timeline',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='apps_settings.academictimeline'),
        ),
    ]
