# Generated by Django 3.2.6 on 2022-03-10 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_students', '0003_alter_enrollments_timeline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollments',
            options={'ordering': ['reg_no', 'session_id']},
        ),
        migrations.RemoveField(
            model_name='enrollments',
            name='class_id',
        ),
    ]
