# Generated by Django 3.2.6 on 2022-03-10 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0015_auto_20220309_1331'),
        ('apps_students', '0004_auto_20220311_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollments',
            name='classroom',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.RESTRICT, to='apps_settings.classrooms'),
            preserve_default=False,
        ),
    ]
