# Generated by Django 3.2.6 on 2022-03-11 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0015_auto_20220309_1331'),
        ('apps_students', '0005_enrollments_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollments',
            name='session_id',
        ),
        migrations.AddField(
            model_name='enrollments',
            name='session',
            field=models.ForeignKey(blank=True, default=14, on_delete=django.db.models.deletion.RESTRICT, to='apps_settings.academicsessions'),
            preserve_default=False,
        ),
    ]
