# Generated by Django 3.2.6 on 2022-03-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0015_auto_20220309_1331'),
        ('apps_students', '0006_auto_20220311_1602'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollments',
            unique_together={('school_id', 'session', 'reg_no', 'classroom')},
        ),
    ]
