# Generated by Django 3.2.6 on 2022-03-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_students', '0007_alter_enrollments_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollments',
            options={'ordering': ['reg_no', 'session__term_id']},
        ),
    ]
