# Generated by Django 3.2.6 on 2022-03-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_students', '0008_alter_enrollments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollments',
            options={'ordering': ['timeline__st_dt', 'enroll_date', 'reg_no']},
        ),
    ]
