# Generated by Django 3.2.6 on 2022-03-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_students', '0009_alter_enrollments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='enrollments',
            old_name='reg_id',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='students',
            name='reg_no',
        ),
    ]
