# Generated by Django 3.2.6 on 2022-03-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_students', '0010_auto_20220311_1832'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollments',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='enrollments',
            constraint=models.UniqueConstraint(fields=('school_id', 'timeline', 'reg_no', 'classroom'), name='regno_class_unx'),
        ),
        migrations.AddConstraint(
            model_name='enrollments',
            constraint=models.UniqueConstraint(fields=('school_id', 'timeline', 'student', 'classroom'), name='stud_class_unx'),
        ),
    ]
