# Generated by Django 3.2.6 on 2022-03-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_students', '0011_auto_20220312_0520'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollments',
            name='stud_class_unx',
        ),
        migrations.AddConstraint(
            model_name='enrollments',
            constraint=models.UniqueConstraint(fields=('school_id', 'timeline', 'student'), name='stud_class_unx'),
        ),
    ]
