# Generated by Django 3.2.6 on 2022-03-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_students', '0012_auto_20220312_0530'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollments',
            name='regno_class_unx',
        ),
        migrations.AddConstraint(
            model_name='enrollments',
            constraint=models.UniqueConstraint(fields=('school_id', 'timeline', 'reg_no'), name='regno_class_unx'),
        ),
    ]
