# Generated by Django 3.2.6 on 2022-03-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_students', '0013_auto_20220312_0534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollments',
            options={'ordering': ['school_id', 'reg_no']},
        ),
    ]
