# Generated by Django 3.2.6 on 2022-03-17 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0016_auto_20220317_2216'),
        ('apps_students', '0014_alter_enrollments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='reg_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='students',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_settings.schoolprofiles'),
        ),
        migrations.AddConstraint(
            model_name='students',
            constraint=models.UniqueConstraint(fields=('school', 'reg_no'), name='school_regno_unq'),
        ),
    ]
