# Generated by Django 3.2.6 on 2022-03-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0016_auto_20220317_2216'),
        ('apps_students', '0015_auto_20220317_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollments',
            name='school_id',
        ),
        migrations.AddField(
            model_name='enrollments',
            name='school',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.RESTRICT, to='apps_settings.schoolprofiles'),
            preserve_default=False,
        ),
    ]
