# Generated by Django 3.2.6 on 2022-04-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_students', '0016_auto_20220318_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollments',
            name='fee_pkg',
            field=models.BigIntegerField(default=0),
        ),
    ]
