# Generated by Django 3.2.6 on 2022-04-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_students', '0017_enrollments_fee_pkg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollments',
            old_name='enroll_date',
            new_name='trans_date',
        ),
    ]
