# Generated by Django 3.2.6 on 2022-04-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_students', '0018_rename_enroll_date_enrollments_trans_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='age',
        ),
    ]
