# Generated by Django 3.2.6 on 2022-01-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_id', models.IntegerField(db_index=True)),
                ('term_id', models.BigIntegerField()),
                ('descx', models.CharField(max_length=15, unique=True)),
                ('status', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'apps_AcademicSessions',
                'ordering': ['status', 'term_id'],
            },
        ),
        migrations.CreateModel(
            name='AcademicTimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_id', models.IntegerField(db_index=True)),
                ('descx', models.CharField(db_index=True, max_length=25)),
                ('st_dt', models.DateField(null=True)),
                ('ed_dt', models.DateField(null=True)),
                ('status', models.CharField(db_index=True, default='Inactive', max_length=15)),
            ],
            options={
                'db_table': 'apps_AcademicTimeLine',
                'ordering': ['descx'],
            },
        ),
        migrations.CreateModel(
            name='SchoolProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_id', models.IntegerField(db_index=True, unique=True)),
                ('rc_no', models.CharField(max_length=35, null=True, unique=True)),
                ('sch_name', models.CharField(db_index=True, max_length=300, unique=True)),
                ('name_abr', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('sch_addr', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_no', models.CharField(blank=True, db_index=True, max_length=33, null=True)),
                ('email', models.EmailField(db_index=True, max_length=255, null=True, unique=True)),
                ('start_date', models.DateField(blank=True, db_index=True, default=None, null=True)),
                ('prop_name', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('sch_motor', models.CharField(blank=True, max_length=200, null=True)),
                ('sch_logo', models.ImageField(blank=True, default='images/static/schoo-log-education.webp', null=True, upload_to='images')),
                ('no_classrooms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apps_SchoolProfiles',
                'ordering': ['sch_id'],
            },
        ),
        migrations.CreateModel(
            name='AcademicCalender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acad_yr', models.CharField(max_length=30)),
                ('start_dt', models.DateField(blank=True, db_index=True, default=None)),
                ('end_dt', models.DateField(blank=True, db_index=True, default=None)),
                ('term_id', models.BigIntegerField(db_index=True)),
                ('cs_start_dt', models.DateField(blank=True, db_index=True, default=None, null=True)),
                ('cs_end_dt', models.DateField(blank=True, db_index=True, default=None, null=True)),
                ('mb_start_dt', models.DateField(blank=True, db_index=True, default=None, null=True)),
                ('mb_end_dt', models.DateField(blank=True, db_index=True, default=None, null=True)),
                ('hs_start_dt', models.DateField(blank=True, db_index=True, default=None, null=True)),
                ('hs_end_dt', models.DateField(blank=True, db_index=True, default=None, null=True)),
                ('status', models.CharField(max_length=15, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('sch_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='apps_settings.academictimeline')),
            ],
            options={
                'db_table': 'apps_AcademicCalender',
                'ordering': ['status', 'term_id'],
            },
        ),
    ]
