# Generated by Django 3.2.6 on 2022-01-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0003_alter_academictimeline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalender',
            name='sch_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='academiccalender',
            name='term_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='academictimeline',
            name='st_dt',
            field=models.DateField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
