# Generated by Django 3.2.6 on 2022-01-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0004_auto_20220121_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalender',
            name='sessx_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='apps_settings.academictimeline'),
        ),
    ]
