# Generated by Django 3.2.6 on 2022-01-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0005_academiccalender_sessx_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academiccalender',
            old_name='sessx_id',
            new_name='tl_id',
        ),
    ]
