# Generated by Django 3.2.6 on 2022-01-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0006_rename_sessx_id_academiccalender_tl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalender',
            name='cs_start_dt',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
