# Generated by Django 3.2.6 on 2022-01-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0007_alter_academiccalender_cs_start_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalender',
            name='cs_start_dt',
            field=models.DateField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
