# Generated by Django 3.2.6 on 2022-02-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0008_alter_academiccalender_cs_start_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalender',
            name='tl_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.RESTRICT, to='apps_settings.academictimeline'),
        ),
    ]
