# Generated by Django 3.2.6 on 2022-02-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0009_alter_academiccalender_tl_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='academictimeline',
            name='s1_ends',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='academictimeline',
            name='s1_starts',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='academictimeline',
            name='s2_ends',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='academictimeline',
            name='s2_starts',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='academictimeline',
            name='s3_ends',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='academictimeline',
            name='s3_starts',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
