# Generated by Django 3.2.6 on 2022-03-08 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0010_auto_20220204_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_room', models.CharField(max_length=25)),
                ('arm', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=10)),
                ('levels', models.IntegerField()),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_settings.schoolprofiles')),
            ],
            options={
                'unique_together': {('school', 'class_room', 'arm')},
            },
        ),
    ]
