# Generated by Django 3.2.6 on 2022-03-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0011_classrooms'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classrooms',
            table='apps_ClassRooms',
        ),
    ]
