# Generated by Django 3.2.6 on 2022-03-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0012_alter_classrooms_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classrooms',
            old_name='class_room',
            new_name='class_name',
        ),
        migrations.AddField(
            model_name='classrooms',
            name='class_abr',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='classrooms',
            unique_together={('school', 'class_abr', 'arm')},
        ),
    ]
