# Generated by Django 3.2.6 on 2022-03-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0013_auto_20220309_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classrooms',
            old_name='school',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='classrooms',
            unique_together={('profile', 'class_abr', 'arm')},
        ),
    ]
