# Generated by Django 3.2.6 on 2022-03-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0014_auto_20220309_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classrooms',
            options={'ordering': ['profile', 'levels']},
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='class_name',
            field=models.CharField(max_length=55),
        ),
    ]
