# Generated by Django 3.2.6 on 2022-03-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0015_auto_20220309_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofiles',
            name='id',
        ),
        migrations.AlterField(
            model_name='schoolprofiles',
            name='sch_id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
