# Generated by Django 3.2.6 on 2022-04-16 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0016_auto_20220317_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalender',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='apps_settings.schoolprofiles'),
        ),
    ]
