# Generated by Django 3.2.6 on 2022-04-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0017_academiccalender_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academiccalender',
            options={'ordering': ['school', 'status', 'term_id']},
        ),
        migrations.AlterField(
            model_name='academiccalender',
            name='sch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
