# Generated by Django 3.2.6 on 2022-03-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_settings', '0016_auto_20220317_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('fee_amount', models.DecimalField(decimal_places=10, max_digits=10)),
                ('status', models.CharField(max_length=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='apps_settings.schoolprofiles')),
            ],
        ),
        migrations.CreateModel(
            name='FeesPackageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField()),
                ('item_descx', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_financials.feespackage')),
            ],
        ),
    ]
