# Generated by Django 3.2.6 on 2022-03-22 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0016_auto_20220317_2216'),
        ('apps_financials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feespackage',
            options={'ordering': ['school', 'id']},
        ),
        migrations.AlterModelOptions(
            name='feespackagedetails',
            options={'ordering': ['school', 'id']},
        ),
        migrations.AddField(
            model_name='feespackagedetails',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='apps_settings.schoolprofiles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feespackage',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_settings.schoolprofiles'),
        ),
        migrations.AddConstraint(
            model_name='feespackagedetails',
            constraint=models.UniqueConstraint(fields=('school', 'package'), name='fees_package_unq'),
        ),
        migrations.AlterModelTable(
            name='feespackage',
            table='apps_FeesPackage',
        ),
        migrations.AlterModelTable(
            name='feespackagedetails',
            table='apps_FeesPackageDetails',
        ),
    ]
