# Generated by Django 3.2.6 on 2022-03-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_financials', '0002_auto_20220322_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feespackage',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feespackagedetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
