# Generated by Django 3.2.6 on 2022-03-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_financials', '0003_auto_20220322_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feespackage',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feespackage',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
