# Generated by Django 3.2.6 on 2022-03-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_financials', '0004_auto_20220325_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feespackagedetails',
            name='item_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
