# Generated by Django 3.2.6 on 2022-03-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_financials', '0005_alter_feespackagedetails_item_no'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feespackagedetails',
            name='fees_package_unq',
        ),
    ]
