# Generated by Django 3.2.6 on 2022-03-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_financials', '0006_remove_feespackagedetails_fees_package_unq'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feespackage',
            constraint=models.UniqueConstraint(fields=('school', 'description'), name='school_descx_unq'),
        ),
    ]
