# Generated by Django 3.2.6 on 2022-03-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_financials', '0007_feespackage_school_descx_unq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feespackage',
            old_name='fee_amount',
            new_name='total_fees',
        ),
    ]
