# Generated by Django 3.2.6 on 2022-04-01 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_financials', '0008_rename_fee_amount_feespackage_total_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feespackagedetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_details', to='apps_financials.feespackage'),
        ),
    ]
