# Generated by Django 3.2.6 on 2022-04-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_financials', '0010_feespackage_pkg_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feespackage',
            name='pkg_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
