# Generated by Django 3.2.6 on 2022-04-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_financials', '0011_alter_feespackage_pkg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feespackage',
            name='pkg_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feespackage',
            name='pkg_type',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
