# Generated by Django 3.2.6 on 2022-04-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_financials', '0012_auto_20220407_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feespackage',
            name='pkg_type_id',
        ),
    ]
