# Generated by Django 3.2.6 on 2022-04-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_students', '0017_enrollments_fee_pkg'),
        ('apps_settings', '0016_auto_20220317_2216'),
        ('apps_financials', '0013_remove_feespackage_pkg_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField()),
                ('invoice_no', models.IntegerField(blank=True, null=True)),
                ('receipt_no', models.CharField(blank=True, max_length=60, null=True)),
                ('descx', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('run_bal', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tr_type', models.CharField(max_length=10)),
                ('enrolled', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='enrolled', to='apps_students.enrollments')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='apps_settings.schoolprofiles')),
            ],
            options={
                'db_table': 'apps_FinancialTransactions',
                'ordering': ['school', 'id'],
            },
        ),
    ]
