# Generated by Django 3.2.6 on 2022-04-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_financials', '0014_financialtransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialtransactions',
            name='run_bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
