# Generated by Django 3.2.6 on 2022-04-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_financials', '0015_auto_20220411_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransactions',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
