# Generated by Django 3.2.6 on 2022-04-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_financials', '0016_alter_financialtransactions_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransactions',
            name='invoice_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
