# Generated by Django 3.2.6 on 2022-04-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_students', '0018_rename_enroll_date_enrollments_trans_date'),
        ('apps_financials', '0017_alter_financialtransactions_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransactions',
            name='enrolled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='enrollment', to='apps_students.enrollments'),
        ),
    ]
