# Generated by Django 3.2.6 on 2022-04-14 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0016_auto_20220317_2216'),
        ('apps_students', '0019_remove_students_age'),
        ('apps_financials', '0018_alter_financialtransactions_enrolled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField()),
                ('invoice_no', models.IntegerField(blank=True, null=True)),
                ('descx', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='apps_financials.feespackage')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='apps_settings.schoolprofiles')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='apps_students.students')),
            ],
            options={
                'db_table': 'apps_Invoice',
                'ordering': ['school', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('school', 'invoice_no'), name='school_Invoice_unq'),
        ),
    ]
