# Generated by Django 3.2.6 on 2022-04-15 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_students', '0019_remove_students_age'),
        ('apps_financials', '0019_auto_20220414_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='enrolled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='invoice', to='apps_students.enrollments'),
        ),
    ]
