# Generated by Django 3.2.6 on 2022-04-21 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_financials', '0020_invoice_enrolled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['school', 'invoice_no']},
        ),
    ]
